# Generated by Django 3.2.5 on 2022-04-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('countryOfOrigin', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255)),
                ('plusSize', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=1023)),
                ('discount', models.FloatField(default=0)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleClothes',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('petite', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=255)),
                ('occasion', models.CharField(max_length=255)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='KidClothes',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('gender', models.CharField(max_length=255)),
                ('recommendedAge', models.CharField(max_length=255)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='MaleClothes',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('tallFit', models.BooleanField(default=False)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='ClothesItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/clothes_items_images/')),
                ('index', models.IntegerField()),
                ('clothesItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothesitem')),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('length', models.FloatField()),
                ('style', models.CharField(max_length=255)),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='FemalePant',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('bottomsLength', models.FloatField()),
                ('waistHeight', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='FemaleShirt',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('neckline', models.CharField(max_length=255)),
                ('croppedTop', models.BooleanField(default=False)),
                ('topLength', models.FloatField()),
                ('sleeveLength', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='MalePant',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('length', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='MaleShirt',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('sleeveLength', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
    ]
