# Generated by Django 3.2.5 on 2022-04-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesitem',
            name='clothes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes'),
        ),
    ]
