# Generated by Django 3.2.5 on 2022-04-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothesitem_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesitem',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes'),
        ),
        migrations.AlterField(
            model_name='clothesitemimage',
            name='clothesItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothes.clothesitem'),
        ),
    ]
