# Generated by Django 3.2.5 on 2022-04-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20220411_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothesitem',
            old_name='prices',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='clothesitem',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothesItems', to='clothes.clothes'),
        ),
    ]
