# Generated by Django 3.2.5 on 2022-04-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookitem_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.book'),
        ),
    ]
