# Generated by Django 3.2.5 on 2022-04-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookitem_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitemimage',
            name='index',
        ),
    ]
